name: Proxy Label Check

on:
  pull_request:
    types:
      - labeled

jobs:
  check-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get PR labels
        id: labels
        uses: actions/github-script@v6
        with:
          script: |
            const labels = context.payload.pull_request.labels.map(label => label.name);
            return labels;
          result-encoding: string

      - name: Filter labels for "test"
        id: filter
        run: |
          echo "Checking for test labels..."
          echo "${{ steps.labels.outputs.result }}" | grep -i "test" || exit 1

      - name: Trigger Dispatch Workflow
        if: success()
        run: |
          COMMIT_SHA=${{ github.event.pull_request.head.sha }}
          echo "Triggering workflow for commit: $COMMIT_SHA"
          gh workflow run dispatch-test-workflow.yml
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
