name: PR Label Trigger Workflow

on:
  pull_request:
    types:
      - labeled

jobs:
  handle-label:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Check out code
        uses: actions/checkout@v3

      # Step 2: Identify the added label
      - name: Display added label
        run: |
          echo "Label added: ${{ github.event.label.name }}"
          echo "PR Title: ${{ github.event.pull_request.title }}"
          echo "PR Number: ${{ github.event.pull_request.number }}"

      # Step 3: Conditional task based on the label
      - name: Run tasks based on label
        run: |
          if [[ "${{ github.event.label.name }}" == "run-tests" ]]; then
            echo "Running tests because 'run-tests' label was added."
            # Add test commands here
          elif [[ "${{ github.event.label.name }}" == "documentation" ]]; then
            echo "Updating documentation because 'documentation' label was added."
            # Add documentation update commands here
          else
            echo "No action for this label."
