name: Proxy Label Check

on:
  pull_request:
    types:
      - labeled

jobs:
  check-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get PR labels
        id: labels
        uses: actions/github-script@v6
        with:
          script: |
            const labels = context.payload.pull_request.labels.map(label => label.name);
            return labels.filter(label => label.toLowerCase().includes("test"));
          result-encoding: string

      - name: Debug matching labels
        run: |
          echo "Matching labels: ${{ steps.labels.outputs.result }}"
        env:
          LABELS: ${{ steps.labels.outputs.result }}

      - name: Trigger Dispatch Workflow for Each Label
        if: ${{ steps.labels.outputs.result != '' }}
        run: |
          for label in $(echo "${{ steps.labels.outputs.result }}" | jq -r '.[]'); do
            echo "Triggering dispatch workflow for label: $label"
            gh workflow run dispatch-test-workflow.yml --ref "${{ github.event.pull_request.head.ref }}"
          done
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
